### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by nicolasnoble** [Zalastax/no-one-left-behind#1]
Just... why ?

**Comment by Zalastax** [comment]
[That's](https://en.wikipedia.org/wiki/Creative_coding) [the](https://en.wikipedia.org/wiki/Anti-art) [question!](https://gist.github.com/anvaka/8e8fa57c7ee1350e3491#file-02-with-most-dependencies-md)

P.S.
It was interesting to see that there is a limitation when uploading to NPM.

**Comment by jtpio** [comment]
It's a good to generate test files and try commands such as `find . -type f -name "*.js" -delete` :nerd_face:

**Comment by jvandenaardweg** [comment]
Please explain the why better. It just looks stupid to me :-) 

Time could have been spend to add value in the open source community, but I fail to see it here.
