### ISSUE TITLE
cant unpublish one of my own packages cause it's in your dependenceis

### ISSUE THREAD

**Issue by marxus** [Zalastax/no-one-left-behind#4]
now i'm stuck with stuff i dont want on my account 

"a_watcher"
https://www.npmjs.com/package/a_watcher

care to somehow help with this issue?

**Comment by Zalastax** [comment]
Can't you force deletion? This is just a joke project so no problem if it breaks.

**Comment by marxus** [comment]
npm ERR! 405 Method Not Allowed - DELETE https://registry.npmjs.org/a_watcher/-rev/5-2991e29ae0f9beb4e3999c5410ea5d69 - You can no longer unpublish this package.
npm ERR! Failed criteria: 
npm ERR! has dependent packages in the registry

**Comment by Zalastax** [comment]
Interesting.

It won't help that I remove you though, from https://docs.npmjs.com/cli/unpublish:

> With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 72 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com.

**Comment by marxus** [comment]
i think i'll contact support...

**Comment by marxus** [comment]
hey man

support helped me ( that was quick!!! ) and removed my package
so https://www.npmjs.com/package/no-one-left-behind is now broken :) 
(but i guess it was broken even from before)

so enjoy :+1:  and enjoy :)

**Comment by Maxim-Mazurok** [comment]
Sounds like it should be closed. Interesting stuff :)

**Comment by Zalastax** [comment]
Happy that it worked out!

**Comment by donmccurdy** [comment]
Note that the npm unpublish policy (which `--force` does not circumvent) for packages older than 72 hours is now:

> Regardless of how long ago a package was published, you can unpublish a package that:
> - **no other packages in the npm Public Registry depend on**
> - had less than 300 downloads over the last week
> - has a single owner/maintainer

https://docs.npmjs.com/policies/unpublish
